INSERT INTO characters (name_character, serie_id) VALUES ('Anna Kaboom', 5);
INSERT INTO characters (name_character, serie_id) VALUES ('Zane Truesdale', 2);
INSERT INTO characters (name_character, serie_id) VALUES ('Shay Obsidian', 6);
INSERT INTO characters (name_character, serie_id) VALUES ('Dr. Vellian Crowler', 2);
INSERT INTO characters (name_character, serie_id) VALUES ('Yami Bakura', 1);
INSERT INTO characters (name_character, serie_id) VALUES ('Maximillion Pegasus', 1);
INSERT INTO characters (name_character, serie_id) VALUES ('Yugi Muto DM', 1);
INSERT INTO characters (name_character, serie_id) VALUES ('Sora Perse', 6);
INSERT INTO characters (name_character, serie_id) VALUES ('Kite Tenjo', 5);
INSERT INTO characters (name_character, serie_id) VALUES ('The Gore', 7);